spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messager
    username: messageruser
    driver-class-name: org.postgresql.Driver
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.change-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect